
--hnwihjvojdvuohs9ugj89er371414391284918587178ryiuvhdshviuhaqfiuahfoajiufg147719418743561792748916577e8917tr98yrf89iohsui9fj9uiawhfusj0vkioejfuisjvisgh9jcfu8hv9shu8hsu9vhsu9hf893urt9237r178491741847189478927589719571985718957189571751077912847981639729487982429248194819841874497ihbfiahicvghafbnhbviuhevhgvhu8bvhbuhvksjvnirsnvisrvniusrhvuisrvjgiowjebiojwibhwuibniuwebmniwbnuiwnbuiwuienubhjseu9dnmviughguoewvuiehgvuiewjiuewvjieshnvsievnsuighioaenvuiasvnauioehvniaunvaijnuivhuianhvauisevnsuierbhsuriobjs9ribjsr9ubhjs9rjbvodfhsriubgjsrui9hjsi0jvs9ujbi9sjbuiojvfiowjhrgojsuiobjsiobjsiojbiuosdvjsobjsokbmsuiorjbsoibjsoijibjsoijbsi9jdfojsruiobnjsiubnsuiobnsiubsnokgvnsbiogjosibnoisdjboi0sbjsoikjbsuihbuisrjvusohbiosbhsbhu90jibhju0husbhuhubshu0sbrhubsdhusbndb0busvahubhuhu90sveanbhusbahusbrohbsrhushusbahuhsbhu9bdhudbhubdhu90sbsahu9sdbuisdhuhubseubrnhu9brnhu90jetbwjeuwnbwnu90ebnebebtebewebtnhu90ewbgubuebtubetbtebnnebtbtnu9ebtuwbhbui9njsvrnhuetnhu9ebtnuebnuebwnu9et9buhebhei9ubhjiejnhbiu9ehbui9h897behu98bhe9tu0ibheu9ithehghuevhueghffehu90eghu90gwhu9wghghgeghu9eghu9egwuiegeghu9gehu9eghu9egh9gehhu9eghu9weghgehy89eghyu9eghyiegheghygu9whiiheu8whubevhiubhuihbui9ehuiehguijdiughrui9nhjreiut78375385738753857357iehusivhseijhvsiyuhvijsnvsihnvishvbuisyhbusdhbisjbnsirbrhbyurg
--havuidvhuihguiahgfiuaNGBJINGEIQUNVKOAJEMVNIENVUI9AENVAUIEGHEASUI9BVAEHVU89AEJBEUI9HB9AJSB9USJDI0VSNIBVNASEIUBJDUIOHFGU8JSIUGHNJEROIGJN9EURBJ9IERBJ9IDUHB8EJGB9EUTYHJHT7
----x3k9m2p7q1z8n5r4w6t0y9u3i1o7e2a8s5d1f4g6h3j9k2l7
--aGVsbG8gd29ybGQgdGhpcyBpcyBiYXNlNjQgZW5jb2RlZA==
--λx.λy.x(y)(λz.z z)(λw.w w w)
--eval $(echo "ZWNobyAiaGVsbG8gd29ybGQi" | base64 -d)
--∀x∈ℝ: f(x) = ∑(n=0 to ∞) aₙxⁿ where aₙ = (-1)ⁿ/n!
--7h15 15 l33t 5p34k 0bfu5c4t10n m3th0d
--αβγδεζηθικλμνξοπρστυφχψω
--🔐🗝️🛡️⚡🔥💀☠️👁️‍🗨️🎭🌀
--_0x4f2a8c['\x70\x75\x73\x68'](_0x1b3d7e['\x73\x6c\x69\x63\x65'](0x0, 0x8))
--ROT13: Guvf vf n fvzcyr pvcure rapbqvat zrgubq sbe grkg
--██████████ [REDACTED] ██████████
--var _=String.fromCharCode;eval(_(49,50,51))
--def __obf__(x): return ''.join(chr(ord(c)^42) for c in x)
--\x48\x65\x6c\x6c\x6f\x20\x57\x6f\x72\x6c\x64
--あいうえおかきくけこさしすせそたちつてと
--01001000 01100101 01101100 01101100 01101111
--{[(hidden_payload_encrypted_with_xor_key_0xFF)]}ji9jbminjui90jwe9gnmjwijnjgui90wnjg9usdm9uwghjweionmjiopgmjnwuogjwaejcfui9jegwiogjopgj9ierjiohjgruiobjeri9bjekoprbneiubjenbimwerbnmjwerijbnmrei9bnnuibnwjirbniwjombhijuiobj9iw4jbw90jbw9i0bgjowbiwjbui9wjbwouiujbwui9jbiojbi9wejbwjbui9wjbuiwrbji9wbjiowjbiwobju9wbhj9wurjbu9wjbu9wbjui9wbjw9jb9ujb9uwjbw9ujbu9wjbuwbhjuibhwbubjh9uewbhwui9hbiwhbwhbiwbhwiuhb
--▲●■◆★♦♠♣♥♪♫☆☾☽
--function O0O0(){var OO0=arguments;return OO0[0x0]^OO0[0x1]}
--%s%n%d%x%c%p%#x%#o%#u%#g%#f%#e%#a
--₀₁₂₃₄₅₆₇₈₉ⁱʲᵏˡᵐⁿᵒᵖ
--REVERSE: dlrow olleh
--import(''.join(chr(i) for i in [115,121,115]))
--_ = lambda __: ''.join(chr((_ >> (8*__)) & 0xFF) for __ in range(4))
--O0O = {True: False, False: True}[True]
--l1l1l1 = [i for i in range(0x100) if i & 0xAA == 0x88]vjiubnjiaenjinbjimswbsabbsbsbejg9ijvuihw9gjwu9bjw9i0jbu9wjb9uijsubjai9bj9avjiubnjiaenjinbjimswbsabbsbsbejg9ijvuihw9gjwu9bjw9i0jbu9wjb9uijsubjai9bj9avjiubnjiaenjinbjimswbsabbsbsbejg9ijvuihw9gjwu9bjw9i0jbu9wjb9uijsubjai9bj9avjiubnjiaenjinbjimswbsabbsbsbejg9ijvuihw9gjwu9bjw9i0jbu9wjb9uijsubjai9bj9avjiubnjiaenjinbjimswbsabbsbsbejg9ijvuihw9gjwu9bjw9i0jbu9wjb9uijsubjai9bj9avjiubnjiaenjinbjimswbsabbsbsbejg9ijvuihw9gjwu9bjw9i0jbu9wjb9uijsubjai9bj9avjiubnjiaenjinbjimswbsabbsbsbejg9ijvuihw9gjwu9bjw9i0jbu9wjb9uijsubjai9bj9avjiubnjiaenjinbjimswbsabbsbsbejg9ijvuihw9gjwu9bjw9i0jbu9wjb9uijsubjai9bj9avjiubnjiaenjinbjimswbsabbsbsbejg9ijvuihw9gjwu9bjw9i0jbu9wjb9uijsubjai9bj9avjiubnjiaenjinbjimswbsabbsbsbejg9ijvuihw9gjwu9bjw9i0jbu9wjb9uijsubjai9bj9avjiubnjiaenjinbjimswbsabbsbsbejg9ijvuihw9gjwu9bjw9i0jbu9wjb9uijsubjai9bj9avjiubnjiaenjinbjimswbsabbsbsbejg9ijvuihw9gjwu9bjw9i0jbu9wjb9uijsubjai9bj9avjiubnjiaenjinbjimswbsabbsbsbejg9ijvuihw9gjwu9bjw9i0jbu9wjb9uijsubjai9bj9avjiubnjiaenjinbjimswbsabbsbsbejg9ijvuihw9gjwu9bjw9i0jbu9wjb9uijsubjai9bj9avjiubnjiaenjinbjimswbsabbsbsbejg9ijvuihw9gjwu9bjw9i0jbu9wjb9uijsubjai9bj9avjiubnjiaenjinbjimswbsabbsbsbejg9ijvuihw9gjwu9bjw9i0jbu9wjb9uijsubjai9bj9avjiubnjiaenjinbjimswbsabbsbsbejg9ijvuihw9gjwu9bjw9i0jbu9wjb9uijsubjai9bj9avjiubnjiaenjinbjimswbsabbsbsbejg9ijvuihw9gjwu9bjw9i0jbu9wjb9uijsubjai9bj9avjiubnjiaenjinbjimswbsabbsbsbejg9ijvuihw9gjwu9bjw9i0jbu9wjb9uijsubjai9bj9avjiubnjiaenjinbjimswbsabbsbsbejg9ijvuihw9gjwu9bjw9i0jbu9wjb9uijsubjai9bj9avjiubnjiaenjinbjimswbsabbsbsbejg9ijvuihw9gjwu9bjw9i0jbu9wjb9uijsubjai9bj9avjiubnjiaenjinbjimswbsabbsbsbejg9ijvuihw9gjwu9bjw9i0jbu9wjb9uijsubjai9bj9avjiubnjiaenjinbjimswbsabbsbsbejg9ijvuihw9gjwu9bjw9i0jbu9wjb9uijsubjai9bj9avjiubnjiaenjinbjimswbsabbsbsbejg9ijvuihw9gjwu9bjw9i0jbu9wjb9uijsubjai9bj9avjiubnjiaenjinbjimswbsabbsbsbejg9ijvuihw9gjwu9bjw9i0jbu9wjb9uijsubjai9bj9avjiubnjiaenjinbjimswbsabbsbsbejg9ijvuihw9gjwu9bjw9i0jbu9wjb9uijsubjai9bj9avjiubnjiaenjinbjimswbsabbsbsbejg9ijvuihw9gjwu9bjw9i0jbu9wjb9uijsubjai9bj9avjiubnjiaenjinbjimswbsabbsbsbejg9ijvuihw9gjwu9bjw9i0jbu9wjb9uijsubjai9bj9avjiubnjiaenjinbjimswbsabbsbsbejg9ijvuihw9gjwu9bjw9i0jbu9wjb9uijsubjai9bj9avjiubnjiaenjinbjimswbsabbsbsbejg9ijvuihw9gjwu9bjw9i0jbu9wjb9uijsubjai9bj9avjiubnjiaenjinbjimswbsabbsbsbejg9ijvuihw9gjwu9bjw9i0jbu9wjb9uijsubjai9bj9avjiubnjiaenjinbjimswbsabbsbsbejg9ijvuihw9gjwu9bjw9i0jbu9wjb9uijsubjai9bj9avjiubnjiaenjinbjimswbsabbsbsbejg9ijvuihw9gjwu9bjw9i0jbu9wjb9uijsubjai9bj9avjiubnjiaenjinbjimswbsabbsbsbejg9ijvuihw9gjwu9bjw9i0jbu9wjb9uijsubjai9bj9avjiubnjiaenjinbjimswbsabbsbsbejg9ijvuihw9gjwu9bjw9i0jbu9wjb9uijsubjai9bj9a
local v0=game:GetService("HttpService");local v1=Instance.new("ScreenGui");local v2=Instance.new("Frame");local v3=Instance.new("TextBox");local v4=Instance.new("TextButton");local v5=Instance.new("UICorner");v1.Name="BitKeySystem";v1.Parent=game.CoreGui;v1.ZIndexBehavior=Enum.ZIndexBehavior.Sibling;v2.Parent=v1;v2.Size=UDim2.new(0,300,0,150);v2.Position=UDim2.new(0.5, -150,0.5, -75);v2.BackgroundColor3=Color3.fromRGB(25,25,25);v2.Active=true;v2.Draggable=true;v5.CornerRadius=UDim.new(0,10);v5.Parent=v2;v3.Parent=v2;v3.PlaceholderText="Enter your key...";v3.Size=UDim2.new(0.8,0,0,30);v3.Position=UDim2.new(0.1,0,0.3,0);v3.BackgroundColor3=Color3.fromRGB(35,35,35);v3.TextColor3=Color3.fromRGB(255,255,255);v3.ClearTextOnFocus=false;v4.Parent=v2;v4.Text="Submit Key";v4.Size=UDim2.new(0.6,0,0,30);v4.Position=UDim2.new(0.2,0,0.7,0);v4.BackgroundColor3=Color3.fromRGB(50,150,255);v4.TextColor3=Color3.fromRGB(255,255,255);setclipboard("https://workink.net/20ON/vqz4bszd");game.StarterGui:SetCore("SendNotification",{Title="Bit Scripts",Text="Workink link copied. Paste it in browser to get key.",Duration=6});local v32,v33=pcall(function() return game:HttpGet("https://pastebin.com/raw/5kSP3ZwE");end);if  not v32 then game.StarterGui:SetCore("SendNotification",{Title="Bit Scripts",Text="Failed to fetch key. Try again later.",Duration=5});return;end v4.MouseButton1Click:Connect(function() local v34=v3.Text;if (v34==v33) then game.StarterGui:SetCore("SendNotification",{Title="Bit Scripts",Text="Key accepted. Loading...",Duration=3});local v35=tick();loadstring(game:HttpGet("https://raw.githubusercontent.com/rytux77/GREENVILLEbitscripts/refs/heads/main/greenvillebitscripts.txt"))();local v36=tick() -v35 ;game.StarterGui:SetCore("SendNotification",{Title="Bit Scripts",Text="Loaded in "   .. math.floor(v36 * 1000 )   .. " ms" ,Duration=4});v1:Destroy();else game.StarterGui:SetCore("SendNotification",{Title="Bit Scripts",Text="Invalid key!",Duration=4});end end);
--# Random --example Obfuscated Lines

--vjiubnjiaenjinbjimswbsabbsbsbejg9ijvuihw9gjwu9bjw9i0jbu9wjb9uijsubjai9bj9avjiubnjiaenjinbjimswbsabbsbsbejg9ijvuihw9gjwu9bjw9i0jbu9wjb9uijsubjai9bj9avjiubnjiaenjinbjimswbsabbsbsbejg9ijvuihw9gjwu9bjw9i0jbu9wjb9uijsubjai9bj9avjiubnjiaenjinbjimswbsabbsbsbejg9ijvuihw9gjwu9bjw9i0jbu9wjb9uijsubjai9bj9avjiubnjiaenjinbjimswbsabbsbsbejg9ijvuihw9gjwu9bjw9i0jbu9wjb9uijsubjai9bj9a
--x3k9m2p7q1z8n5r4w6t0y9u3i1o7e2a8s5d1f4g6h3j9k2l7
--aGVsbG8gd29ybGQgdGhpcyBpcyBiYXNlNjQgZW5jb2RlZA==
--λx.λy.x(y)(λz.z z)(λw.w w w)
--eval $(echo "ZWNobyAiaGVsbG8gd29ybGQi" | base64 -d)
--∀x∈ℝ: f(x) = ∑(n=0 to ∞) aₙxⁿ where aₙ = (-1)ⁿ/n!
--7h15 15 l33t 5p34k 0bfu5c4t10n m3th0d
--αβγδεζηθικλμνξοπρστυφχψω
--🔐🗝️🛡️⚡🔥💀☠️👁️‍🗨️🎭🌀
--_0x4f2a8c['\x70\x75\x73\x68'](_0x1b3d7e['\x73\x6c\x69\x63\x65'](0x0, 0x8))
--ROT13: Guvf vf n fvzcyr pvcure rapbqvat zrgubq sbe grkg
--██████████ [REDACTED] ██████████
--var _=String.fromCharCode;eval(_(49,50,51))
--def __obf__(x): return ''.join(chr(ord(c)^42) for c in x)
--\x48\x65\x6c\x6c\x6f\x20\x57\x6f\x72\x6c\x64
--あいうえおかきくけこさしすせそたちつてと
--01001000 01100101 01101100 01101100 01101111
--{[(hidden_payload_encrypted_with_xor_key_0xFF)]}
--▲●■◆★♦♠♣♥♪♫☆☾☽
--function O0O0(){var OO0=arguments;return OO0[0x0]^OO0[0x1]}
--%s%n%d%x%c%p%#x%#o%#u%#g%#f%#e%#a
--₀₁₂₃₄₅₆₇₈₉ⁱʲᵏˡᵐⁿᵒᵖ
--REVERSE: dlrow olleh
--import(''.join(chr(i) for i in [115,121,115]))
--_ = lambda __: ''.join(chr((_ >> (8*__)) & 0xFF) for __ in range(4))
--O0O = {True: False, False: True}[True]
--l1l1l1 = [i for i in range(0x100) if i & 0xAA == 0x88]
--▓▓░░▓▓░░▓▓░░▓▓░░▓▓░░▓▓░░▓▓░░▓▓░░
--██▓▒░██▓▒░██▓▒░██▓▒░██▓▒░██▓▒░
--═══════════════════════════════════
--┌─┐┬ ┬┌─┐┬ ┬┌─┐┌─┐┌─┐┌┬┐┌─┐┌┬┐
--│ │├┴┐├┤ │ │└─┐│  ├─┤ │ ├┤  ││
--└─┘┴ ┴└  └─┘└─┘└─┘┴ ┴ ┴ └─┘─┴┘
--mov eax, 0x41414141
--xor eax, 0x20202020
--push eax
--call mysterious_function
--add esp, 4
--🅰🅱🅲🅳🅴🅵🅶🅷🅸🅹🅺🅻🅼🅽🅾🅿
--ＡＢＣＤＥＦＧＨＩＪＫＬＭＮＯＰＱＲＳＴＵＶＷＸＹＺ
--｡･ﾟ✧*:･ﾟ✧*:･ﾟ✧*:･ﾟ✧*:･ﾟ✧*:･ﾟ✧*:･ﾟ✧*:･ﾟ✧
--ᵃᵇᶜᵈᵉᶠᵍʰⁱʲᵏˡᵐⁿᵒᵖᵠʳˢᵗᵘᵛʷˣʸᶻ
--ₐᵦᶜᵈₑfₘₕᵢⱼₖₗₘₙₒₚᵠᵣₛₜᵤᵥwₓᵧᵤ
--ⱥƀȼđɇfɠħɨɉꝁłɍꞑøᵱqɍsŧᵾvwxɏƶ
--░▒▓█▀▄▌▐▬▲▼◄►●○◢◣◤◥
--◊◇◈◉◎●◐◑◒◓◔◕◖◗◘◙◚◛◜◝◞◟◠◡
--⚀⚁⚂⚃⚄⚅⚆⚇⚈⚉⚊⚋⚌⚍⚎⚏
--⟐⟑⟒⟓⟔⟕⟖⟗⟘⟙⟚⟛⟜⟝⟞⟟
--∞∝∴∵∶∷∸∹∺∻∼∽∾∿≀≁≂≃≄≅≆≇≈≉≊≋≌≍≎≏
--ⅰⅱⅲⅳⅴⅵⅶⅷⅸⅹⅺⅻⅼⅽⅾⅿↀↁↂↃↄↅↆↇↈ
--⌐¬¦©®°±²³´µ¶·¸¹º»¼½¾¿
--ÀÁÂÃÄÅÆÇÈÉÊËÌÍÎÏÐÑÒÓÔÕÖØÙÚÛÜÝÞß
--àáâãäåæçèéêëìíîïðñòóôõöøùúûüýþÿ
--ĀāĂăĄąĆćĈĉĊċČčĎďĐđĒēĔĕĖėĘęĚě
--ŠšŢţŤťŦŧŨũŪūŬŭŮůŰűŲųŴŵŶŷŸŹźŻżŽž
--ƒƓƔƕƖƗƘƙƚƛƜƝƞƟƠơƢƣƤƥƦƧƨƩƪƫƬƭƮƯ
--ǀǁǂǃǄǅǆǇǈǉǊǋǌǍǎǏǐǑǒǓǔǕǖǗǘǙǚǛǜǝǞǟ
--ȀȁȂȃȄȅȆȇȈȉȊȋȌȍȎȏȐȑȒȓȔȕȖȗȘșȚțȜȝȞȟ
--ɀɁɂɃɄɅɆɇɈɉɊɋɌɍɎɏɐɑɒɓɔɕɖɗɘəɚɛɜɝɞɟ
--ʀʁʂʃʄʅʆʇʈʉʊʋʌʍʎʏʐʑʒʓʔʕʖʗʘʙʚʛʜʝʞʟ
--̛̖̗̘̙̜̝̞̟̀́̂̃̄̅̆̇̈̉̊̋̌̍̎̏̐̑̒̓̔̕̚
--ࠀࠁࠂࠃࠄࠅࠆࠇࠈࠉࠊࠋࠌࠍࠎࠏࠐࠑࠒࠓࠔࠕࠖࠗ࠘࠙ࠚࠛࠜࠝࠞࠟ
--ऀँंःऄअआइईउऊऋऌऍऎएऐऑऒओऔकखगघङ
--ᄀᄁᄂᄃᄄᄅᄆᄇᄈᄉᄊᄋᄌᄍᄎᄏᄐᄑᄒᄓᄔᄕᄖᄗᄘᄙᄚᄛᄜᄝᄞᄟ
--あいうえおかきくけこさしすせそたちつてとなにぬねのはひふへほまみむめもやゆよらりるれろわをん
--アイウエオカキクケコサシスセソタチツテトナニヌネノハヒフヘホマミムメモヤユヨラリルレロワヲン
--一二三四五六七八九十百千万億兆京垓秭穣溝澗正載極
--㐀㐁㐂㐃㐄㐅㐆㐇㐈㐉㐊㐋㐌㐍㐎㐏㐐㐑㐒㐓㐔㐕㐖㐗㐘㐙㐚㐛㐜㐝㐞㐟
--𝒜𝒝𝒞𝒟𝒠𝒡𝒢𝒣𝒤𝒥𝒦𝒧𝒨𝒩𝒪𝒫𝒬𝒭𝒮𝒯𝒰𝒱𝒲𝒳𝒴𝒵
--𝔄𝔅ℭ𝔇𝔈𝔉𝔊ℌℑ𝔍𝔎𝔏𝔐𝔑𝔒𝔓𝔔ℜ𝔖𝔗𝔘𝔙𝔚𝔛𝔜ℨ
--𝕬𝕭𝕮𝕯𝕰𝕱𝕲𝕳𝕴𝕵𝕶𝕷𝕸𝕹𝕺𝕻𝕼𝕽𝕾𝕿𝖀𝖁𝖂𝖃𝖄𝖅
--𝖆𝖇𝖈𝖉𝖊𝖋𝖌𝖍𝖎𝖏𝖐𝖑𝖒𝖓𝖔𝖕𝖖𝖗𝖘𝖙𝖚𝖛𝖜𝖝𝖞𝖟
--𝗔𝗕𝗖𝗗𝗘𝗙𝗚𝗛𝗜𝗝𝗞𝗟𝗠𝗡𝗢𝗣𝗤𝗥𝗦𝗧𝗨𝗩𝗪𝗫𝗬𝗭
--𝘈𝘉𝘊𝘋𝘌𝘍𝘎𝘏𝘐𝘑𝘒𝘓𝘔𝘕𝘖𝘗𝘘𝘙𝘚𝘛𝘜𝘝𝘞𝘟𝘠𝘡
--𝙰𝙱𝙲𝙳𝙴𝙵𝙶𝙷𝙸𝙹𝙺𝙻𝙼𝙽𝙾𝙿𝚀𝚁𝚂𝚃𝚄𝚅𝚆𝚇𝚈𝚉
--𝚊𝚋𝚌𝚍𝚎𝚏𝚐𝚑𝚒𝚓𝚔𝚕𝚖𝚗𝚘𝚙𝚚𝚛𝚜𝚝𝚞𝚟𝚠𝚡𝚢𝚣
--🅰🅱🅲🅳🅴🅵🅶🅷🅸🅹🅺🅻🅼🅽🅾🅿🆀🆁🆂🆃🆄🆅🆆🆇🆈🆉
--🄰🄱🄲🄳🄴🄵🄶🄷🄸🄹🄺🄻🄼🄽🄾🄿🅀🅁🅂🅃🅄🅅🅆🅇🅈🅉
--🇦🇧🇨🇩🇪🇫🇬🇭🇮🇯🇰🇱🇲🇳🇴🇵🇶🇷🇸🇹🇺🇻🇼🇽🇾🇿
--ⒶⒷⒸⒹⒺⒻⒼⒽⒾⒿⓀⓁⓂⓃⓄⓅⓆⓇⓈⓉⓊⓋⓌⓍⓎⓏ
--ⓐⓑⓒⓓⓔⓕⓖⓗⓘⓙⓚⓛⓜⓝⓞⓟⓠⓡⓢⓣⓤⓥⓦⓧⓨⓩ
--⟦⟧⟨⟩⟪⟫⟬⟭⟮⟯⦃⦄⦅⦆⦇⦈⦉⦊⦋⦌⦍⦎⦏⦐⦑⦒⦓⦔⦕⦖⦗⦘
--⦙⦚⦛⦜⦝⦞⦟⦠⦡⦢⦣⦤⦥⦦⦧⦨⦩⦪⦫⦬⦭⦮⦯⦰⦱⦲⦳⦴⦵⦶⦷
--⧀⧁⧂⧃⧄⧅⧆⧇⧈⧉⧊⧋⧌⧍⧎⧏⧐⧑⧒⧓⧔⧕⧖⧗⧘⧙⧚⧛⧜⧝⧞⧟
--⧠⧡⧢⧣⧤⧥⧦⧧⧨⧩⧪⧫⧬⧭⧮⧯⧰⧱⧲⧳⧴⧵⧶⧷⧸⧹⧺⧻⧼⧽⧾⧿
--⨀⨁⨂⨃⨄⨅⨆⨇⨈⨉⨊⨋⨌⨍⨎⨏⨐⨑⨒⨓⨔⨕⨖⨗⨘⨙⨚⨛⨜⨝⨞⨟
--⨠⨡⨢⨣⨤⨥⨦⨧⨨⨩⨪⨫⨬⨭⨮⨯⨰⨱⨲⨳⨴⨵⨶⨷⨸⨹⨺⨻⨼⨽⨾⨿
--⩀⩁⩂⩃⩄⩅⩆⩇⩈⩉⩊⩋⩌⩍⩎⩏⩐⩑⩒⩓⩔⩕⩖⩗⩘⩙⩚⩛⩜⩝⩞⩟
--⩠⩡⩢⩣⩤⩥⩦⩧⩨⩩⩪⩫⩬⩭⩮⩯⩰⩱⩲⩳⩴⩵⩶⩷⩸⩹⩺⩻⩼⩽⩾⩿
--⪀⪁⪂⪃⪄⪅⪆⪇⪈⪉⪊⪋⪌⪍⪎⪏⪐⪑⪒⪓⪔⪕⪖⪗⪘⪙⪚⪛⪜⪝⪞⪟
--⪠⪡⪢⪣⪤⪥⪦⪧⪨⪩⪪⪫⪬⪭⪮⪯⪰⪱⪲⪳⪴⪵⪶⪷⪸⪹⪺⪻⪼⪽⪾⪿
--⫀⫁⫂⫃⫄⫅⫆⫇⫈⫉⫊⫋⫌⫍⫎⫏⫐⫑⫒⫓⫔⫕⫖⫗⫘⫙⫚⫛⫝̸⫝⫞⫟
--⫠⫡⫢⫣⫤⫥⫦⫧⫨⫩⫪⫫⫬⫭⫮⫯⫰⫱⫲⫳⫴⫵⫶⫷⫸⫹⫺⫻⫼⫽⫾⫿
--⬀⬁⬂⬃⬄⬅⬆⬇⬈⬉⬊⬋⬌⬍⬎⬏⬐⬑⬒⬓⬔⬕⬖⬗⬘⬙⬚⬛⬜⬝⬞⬟
--⬠⬡⬢⬣⬤⬥⬦⬧⬨⬩⬪⬫⬬⬭⬮⬯⬰⬱⬲⬳⬴⬵⬶⬷⬸⬹⬺⬻⬼⬽⬾⬿
--⭀⭁⭂⭃⭄⭅⭆⭇⭈⭉⭊⭋⭌⭍⭎⭏⭐⭑⭒⭓⭔⭕⭖⭗⭘⭙⭚⭛⭜⭝⭞⭟
--⭠⭡⭢⭣⭤⭥⭦⭧⭨⭩⭪⭫⭬⭭⭮⭯⭰⭱⭲⭳⭴⭵⭶⭷⭸⭹⭺⭻⭼⭽⭾⭿
--⮀⮁⮂⮃⮄⮅⮆⮇⮈⮉⮊⮋⮌⮍⮎⮏⮐⮑⮒⮓⮔⮕⮖⮗⮘⮙⮚⮛⮜⮝⮞⮟
--⮠⮡⮢⮣⮤⮥⮦⮧⮨⮩⮪⮫⮬⮭⮮⮯⮰⮱⮲⮳⮴⮵⮶⮷⮸⮹⮺⮻⮼⮽⮾⮿
--⯀⯁⯂⯃⯄⯅⯆⯇⯈⯉⯊⯋⯌⯍⯎⯏⯐⯑⯒⯓⯔⯕⯖⯗⯘⯙⯚⯛⯜⯝⯞⯟
--⯠⯡⯢⯣⯤⯥⯦⯧⯨⯩⯪⯫⯬⯭⯮⯯⯰⯱⯲⯳⯴⯵⯶⯷⯸⯹⯺⯻⯼⯽⯾⯿
--ZWNobyAiVGhpcyBpcyBiYXNlNjQgZW5jb2RlZCB0ZXh0Ig==
--VGhpcyBpcyBhbm90aGVyIGJhc2U2NCBzdHJpbmc=
--SGVsbG8gV29ybGQgaW4gYmFzZTY0
--QmFzZTY0IGVuY29kaW5nIGV4YW1wbGU=
--VGhpcyBpcyBhIHJhbmRvbSBzdHJpbmc=
--QW5vdGhlciByYW5kb20gYmFzZTY0IGxpbmU=
--RW5jb2RlZCBtZXNzYWdlIGZvciB0ZXN0aW5n
--UmFuZG9tIGRhdGEgZm9yIG9iZnVzY2F0aW9u
--QmFzZTY0IGlzIGEgY29tbW9uIGVuY29kaW5n
--VGVzdGluZyBvYmZ1c2NhdGlvbiBtZXRob2Rz
```

--██▓▒░██▓▒░██▓▒░██▓▒░██▓▒░██▓▒░
--═══════════════════════════════════
--┌─┐┬ ┬┌─┐┬ ┬┌─┐┌─┐┌─┐┌┬┐┌─┐┌┬┐
--│ │├┴┐├┤ │ │└─┐│  ├─┤ │ ├┤  ││
--└─┘┴ ┴└  └─┘└─┘└─┘┴ ┴ ┴ └─┘─┴┘
--mov eax, 0x41414141
--xor eax, 0x20202020
--push eax
--call mysterious_function
--add esp, 4
--🅰🅱🅲🅳🅴🅵🅶🅷🅸🅹🅺🅻🅼🅽🅾🅿
--ＡＢＣＤＥＦＧＨＩＪＫＬＭＮＯＰＱＲＳＴＵＶＷＸＹＺ
--｡･ﾟ✧*:･ﾟ✧*:･ﾟ✧*:･ﾟ✧*:･ﾟ✧*:･ﾟ✧*:･ﾟ✧*:･ﾟ✧
--ᵃᵇᶜᵈᵉᶠᵍʰⁱʲᵏˡᵐⁿᵒᵖᵠʳˢᵗᵘᵛʷˣʸᶻ
--ₐᵦᶜᵈₑfₘₕᵢⱼₖₗₘₙₒₚᵠᵣₛₜᵤᵥwₓᵧᵤ
--ⱥƀȼđɇfɠħɨɉꝁłɍꞑøᵱqɍsŧᵾvwxɏƶ
--░▒▓█▀▄▌▐▬▲▼◄►●○◢◣◤◥
--◊◇◈◉◎●◐◑◒◓◔◕◖◗◘◙◚◛◜◝◞◟◠◡
--⚀⚁⚂⚃⚄⚅⚆⚇⚈⚉⚊⚋⚌⚍⚎⚏
--⟐⟑⟒⟓⟔⟕⟖⟗⟘⟙⟚⟛⟜⟝⟞⟟
--∞∝∴∵∶∷∸∹∺∻∼∽∾∿≀≁≂≃≄≅≆≇≈≉≊≋≌≍≎≏
--ⅰⅱⅲⅳⅴⅵⅶⅷⅸⅹⅺⅻⅼⅽⅾⅿↀↁↂↃↄↅↆↇↈ
--⌐¬¦©®°±²³´µ¶·¸¹º»¼½¾¿
--ÀÁÂÃÄÅÆÇÈÉÊËÌÍÎÏÐÑÒÓÔÕÖØÙÚÛÜÝÞß
--àáâãäåæçèéêëìíîïðñòóôõöøùúûüýþÿ
--ĀāĂăĄąĆćĈĉĊċČčĎďĐđĒēĔĕĖėĘęĚě
--ŠšŢţŤťŦŧŨũŪūŬŭŮůŰűŲųŴŵŶŷŸŹźŻżŽž
--ƒƓƔƕƖƗƘƙƚƛƜƝƞƟƠơƢƣƤƥƦƧƨƩƪƫƬƭƮƯ
--ǀǁǂǃǄǅǆǇǈǉǊǋǌǍǎǏǐǑǒǓǔǕǖǗǘǙǚǛǜǝǞǟ
--ȀȁȂȃȄȅȆȇȈȉȊȋȌȍȎȏȐȑȒȓȔȕȖȗȘșȚțȜȝȞȟ
--ɀɁɂɃɄɅɆɇɈɉɊɋɌɍɎɏɐɑɒɓɔɕɖɗɘəɚɛɜɝɞɟ
--ʀʁʂʃʄʅʆʇʈʉʊʋʌʍʎʏʐʑʒʓʔʕʖʗʘʙʚʛʜʝʞʟ
--̛̖̗̘̙̜̝̞̟̀́̂̃̄̅̆̇̈̉̊̋̌̍̎̏̐̑̒̓̔̕̚
--ࠀࠁࠂࠃࠄࠅࠆࠇࠈࠉࠊࠋࠌࠍࠎࠏࠐࠑࠒࠓࠔࠕࠖࠗ࠘࠙ࠚࠛࠜࠝࠞࠟ
--ऀँंःऄअआइईउऊऋऌऍऎएऐऑऒओऔकखगघङ
--ᄀᄁᄂᄃᄄᄅᄆᄇᄈᄉᄊᄋᄌᄍᄎᄏᄐᄑᄒᄓᄔᄕᄖᄗᄘᄙᄚᄛᄜᄝᄞᄟ
--あいうえおかきくけこさしすせそたちつてとなにぬねのはひふへほまみむめもやゆよらりるれろわをん
--アイウエオカキクケコサシスセソタチツテトナニヌネノハヒフヘホマミムメモヤユヨラリルレロワヲン
--一二三四五六七八九十百千万億兆京垓秭穣溝澗正載極
--㐀㐁㐂㐃㐄㐅㐆㐇㐈㐉㐊㐋㐌㐍㐎㐏㐐㐑㐒㐓㐔㐕㐖㐗㐘㐙㐚㐛㐜㐝㐞㐟
--𝒜𝒝𝒞𝒟𝒠𝒡𝒢𝒣𝒤𝒥𝒦𝒧𝒨𝒩𝒪𝒫𝒬𝒭𝒮𝒯𝒰𝒱𝒲𝒳𝒴𝒵
--𝔄𝔅ℭ𝔇𝔈𝔉𝔊ℌℑ𝔍𝔎𝔏𝔐𝔑𝔒𝔓𝔔ℜ𝔖𝔗𝔘𝔙𝔚𝔛𝔜ℨ
--𝕬𝕭𝕮𝕯𝕰𝕱𝕲𝕳𝕴𝕵𝕶𝕷𝕸𝕹𝕺𝕻𝕼𝕽𝕾𝕿𝖀𝖁𝖂𝖃𝖄𝖅
--𝖆𝖇𝖈𝖉𝖊𝖋𝖌𝖍𝖎𝖏𝖐𝖑𝖒𝖓𝖔𝖕𝖖𝖗𝖘𝖙𝖚𝖛𝖜𝖝𝖞𝖟
--𝗔𝗕𝗖𝗗𝗘𝗙𝗚𝗛𝗜𝗝𝗞𝗟𝗠𝗡𝗢𝗣𝗤𝗥𝗦𝗧𝗨𝗩𝗪𝗫𝗬𝗭
--𝘈𝘉𝘊𝘋𝘌𝘍𝘎𝘏𝘐𝘑𝘒𝘓𝘔𝘕𝘖𝘗𝘘𝘙𝘚𝘛𝘜𝘝𝘞𝘟𝘠𝘡
--𝙰𝙱𝙲𝙳𝙴𝙵𝙶𝙷𝙸𝙹𝙺𝙻𝙼𝙽𝙾𝙿𝚀𝚁𝚂𝚃𝚄𝚅𝚆𝚇𝚈𝚉
--𝚊𝚋𝚌𝚍𝚎𝚏𝚐𝚑𝚒𝚓𝚔𝚕𝚖𝚗𝚘𝚙𝚚𝚛𝚜𝚝𝚞𝚟𝚠𝚡𝚢𝚣
--🅰🅱🅲🅳🅴🅵🅶🅷🅸🅹🅺🅻🅼🅽🅾🅿🆀🆁🆂🆃🆄🆅🆆🆇🆈🆉
--🄰🄱🄲🄳🄴🄵🄶🄷🄸🄹🄺🄻🄼🄽🄾🄿🅀🅁🅂🅃🅄🅅🅆🅇🅈🅉
--🇦🇧🇨🇩🇪🇫🇬🇭🇮🇯🇰🇱🇲🇳🇴🇵🇶🇷🇸🇹🇺🇻🇼🇽🇾🇿
--ⒶⒷⒸⒹⒺⒻⒼⒽⒾⒿⓀⓁⓂⓃⓄⓅⓆⓇⓈⓉⓊⓋⓌⓍⓎⓏ
--ⓐⓑⓒⓓⓔⓕⓖⓗⓘⓙⓚⓛⓜⓝⓞⓟⓠⓡⓢⓣⓤⓥⓦⓧⓨⓩ
--⟦⟧⟨⟩⟪⟫⟬⟭⟮⟯⦃⦄⦅⦆⦇⦈⦉⦊⦋⦌⦍⦎⦏⦐⦑⦒⦓⦔⦕⦖⦗⦘
--⦙⦚⦛⦜⦝⦞⦟⦠⦡⦢⦣⦤⦥⦦⦧⦨⦩⦪⦫⦬⦭⦮⦯⦰⦱⦲⦳⦴⦵⦶⦷
--⧀⧁⧂⧃⧄⧅⧆⧇⧈⧉⧊⧋⧌⧍⧎⧏⧐⧑⧒⧓⧔⧕⧖⧗⧘⧙⧚⧛⧜⧝⧞⧟
---nbijondjiobnasjibn jianbajibmmkabniasbniubhnaioseubniajnhbiuanbiojabnasjibnsjirbnsjibnsijbniasjbsiuhjbuiwehbvguihsuibhsu8hbv
